version: "3.2"
services:
  node:
      build: .
      ports:
          - 80:51005
      volumes:
          - ./:/code
  mongo:
      image: mongo:latest
      ports:
          - 27017:27017
      volumes:
          - ./mongodb:/data/db

  mysql:
      image: mysql:5.7
      environment:
          MYSQL_DATABASE: 'backend_demo'
          MYSQL_USER: 'sqluser'
          MYSQL_PASSWORD: 'sqluser@123'
          MYSQL_ROOT_PASSWORD: 'admin@123'
      ports:
          - '3306:3306'
      expose:
          - '3306'
      volumes:
          - ./my-db:/var/lib/mysql
